### ISSUE TITLE
Kayıtlı olmayan kullanıcı sisteme kayıt olur.

### ISSUE THREAD

**Issue by alidindar** [mermn/Kan-Bagis-Uygulamasi-#1]

**Comment by mermn** [comment]
Kullanıcı Kabul

1- Ziyaretçi TC Kimlik No ve Şifre alanlarını doldurur.
2- Devam butonuna tıklar.
3- TC Kimlik No ve Şifre veritabanından doğrulanır.
4- Eşleşme yapılırsa kullanıcı sisteme giriş yapar. Değilse uyarı verilir.

Acceptance Test

1- TC Kimlik No ve Şifre alanı dolu mu? Dolu değilse uyarı veriliyor mu?
2- Kullanıcı adı ve şifre eşleşiyor mu? Eşleşmiyor ise uyarı veriliyor mu?
3- TC Kimlik No sistemde kayıtlı mı? Kayıtlı değil ise uyarı veriliyor mu?
