### ISSUE TITLE
Ziyaretçi sisteme kayıt olur.

### ISSUE THREAD

**Issue by alidindar** [mermn/Kan-Bagis-Uygulamasi-#2]

**Comment by alidindar** [comment]
User Story

1-) Kullanıcı giriş düğmesine basar.
2-) Kullanıcı Tc ve Şifre girer.
3-) Kullanıcı sisteme başarı ile girer.

Acceptance Test

1-) Kullanıcı Tc veya şifresini yanlış girebilir.
Bunun için sistem yanlış girdiniz uyarısı sunar.
2-) Kullanıcı Tc yerine harf girebilir.
Bunun için sistem harf girdiniz uyarısı sunar.
3-) Kullanıcı giriş düğmesine bastığında giremeyebilir.
Bunun için sistem üye olunuz uyarısı sunar.

**Comment by mermn** [comment]
1-Tüm alanların doğrulukları kontrol edilir. (TC No, Ad, Soyad, Kan Grubu, Telefon No, e-posta adresi, ...)
2- E-posta adresi kullanımda mı kontrol edilir.
3- Sistem e-posta onayı için posta gönderdi mi kontrol edilir.
4- E-posta 2 dakika içerisinde iletildi mi? Edilmedi ise iptal et.

**Comment by mermn** [comment]
Kayıtlı olmayan kullanıcı kayıt penceresini açabildi mi?
