### ISSUE TITLE
Ziyaretçi e-posta linki ile kaydını tamamlar.

### ISSUE THREAD

**Issue by mertguler** [mermn/Kan-Bagis-Uygulamasi-#3]

**Comment by mermn** [comment]
1- Onay e-postası zamanında iletildi mi?
2- Süre geçmiş ise tekrar gönderim yapıldı mı?
3- Onay e-postası zamanında iletildi ise zamanında tıklandı mı?
4- Zamanında tıklanmadı ise iptal edildi mi?
