### ISSUE TITLE
Kan Vermek İsteyen Kullanıcı bilgi girişi yapar.

### ISSUE THREAD

**Issue by kaanesit** [mermn/Kan-Bagis-Uygulamasi-#6]

**Comment by mermn** [comment]
1- İl, ilçe, hastane alanları dolduruldu mu kontrol edilir.
2- Devam butonuna tıklanırsa onay sayfası açıldı mı? Açılmadı ise uyarı verilir.
4- Geri butonuna tıklanırsa Kan Verme Penceresine dönüldü mü? Dönülmedi ise uyarı verilir.
