### ISSUE TITLE
Kan Vermek isteyen kullanıcı onay verir.

### ISSUE THREAD

**Issue by kaanesit** [mermn/Kan-Bagis-Uygulamasi-#7]

**Comment by mermn** [comment]
1- Onay sayfasında Kan vermek isteyen kullanıcının seçtiği il, ilçe bilgileri gösterildi mi?
2- Devam Butonuna basıldığında onay verildi mi?
3- Geri butonuna basıldığında bir önceki pencereye döndü mü?
